// svelte-kit/src/routes/books/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<section>
    <div class="flex flex-col h-screen items-center justify-center">
        <h1 class="text-4xl font-bold">Books</h1>
        <div>
        {#if data.books.length > 0}
        <ul>
            {#each data.books as book}
                <li>{book.title}</li>
            {/each}
        </ul>
        {:else}
            <p>No books found</p>
        {/if}
        </div>
    </div>
</section>

// remix/app/routes/books/index.tsx
import { useLoaderData } from "@remix-run/react";

export const loader = async () => {
    console.log("server code");
    return [
        { id: 1, title: "The Great Gatsby" },
        { id: 2, title: "The Catcher in the Rye" },
        { id: 3, title: "To Kill a Mockingbird" },
    ] // coming from a database using an ORM
}

export default function Books() {

    const data = useLoaderData<{ id: number, title: string }[]>();
    console.log("client code");

    return (
        <div className="flex flex-col h-screen items-center justify-center">
            <h1 className="text-4xl font-bold">Books</h1>

            <ul>
                {data.map((book) => (
                    <li key={book.id}>{book.title}</li>
                ))}
            </ul>
        </div>
    );
}
