// nextjs/app/books/page.tsx
import { getBooks } from "@/data/services/getBooks";



export default async function BooksPage() {
    const books = await getBooks();

    return (
        <div className="flex flex-col h-screen items-center justify-center">
            <h1 className="text-4xl font-bold">Books</h1>
            <ul>
                {books.map((book) => (
                    <li key={book.id}>{book.title}</li>
                ))}
            </ul>
        </div>
    );
}

// svelte-kit/src/routes/books/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<section>
    <div class="flex flex-col h-screen items-center justify-center">
        <h1 class="text-4xl font-bold">Books</h1>
        <div>
        {#if data.books.length > 0}
        <ul>
            {#each data.books as book}
                <li>{book.title}</li>
            {/each}
        </ul>
        {:else}
            <p>No books found</p>
        {/if}
        </div>
    </div>
</section>
